### ISSUE TITLE
docker-compose file

### ISSUE THREAD

**Issue by installvirtual** [blazeeboy/capistrano-decompose#1]
Hi,

How we can give docker-compose file that has another name. 
Normally we do docker-compose -f (compose).

**Comment by chetankapoor** [comment]
I have opened a pull request for this feature.

**Comment by emad-elsaid** [comment]
sorry for not responding to this fast enough, somehow I don't get notifications for some of my repositories, I apologize.
As I merged the PR today I will close this issue.
